-- Create Table Statesments

CREATE TABLE Warehouse.CHARTEVENTS 
  ( 
    ROW_ID INT NOT NULL, 
  	SUBJECT_ID INT NOT NULL, 
  	HADM_ID INT, 
  	ICUSTAY_ID INT, 
  	ITEMID INT, 
  	CHARTTIME VARCHAR(20), 
  	STORETIME VARCHAR(20), 
  	CGID INT, 
  	[VALUE] VARCHAR(255), 
  	VALUENUM DOUBLE PRECISION, 
  	VALUEUOM VARCHAR(50), 
  	WARNING INT, 
  	ERROR INT, 
  	RESULTSTATUS VARCHAR(50), 
  	[STOPPED] VARCHAR(50), 
  	CONSTRAINT chartevents_rowid_pk PRIMARY KEY (ROW_ID) 
  ); 


CREATE TABLE Warehouse.DATETIMEEVENTS 
  ( 
    ROW_ID INT NOT NULL, 
  	SUBJECT_ID INT NOT NULL, 
  	HADM_ID INT, 
  	ICUSTAY_ID INT, 
  	ITEMID INT NOT NULL, 
  	CHARTTIME VARCHAR(20) NOT NULL, 
  	STORETIME VARCHAR(20) NOT NULL, 
  	CGID INT NOT NULL, 
  	[VALUE] ROWVERSION, 
  	VALUEUOM VARCHAR(50) NOT NULL, 
  	WARNING SMALLINT, 
  	ERROR SMALLINT, 
  	RESULTSTATUS VARCHAR(50), 
  	STOPPED VARCHAR(50), 
  	CONSTRAINT datetime_rowid_pk PRIMARY KEY (ROW_ID) 
  ); 

  
CREATE TABLE Warehouse.ICUSTAYS
  ( 
    ROW_ID INT NOT NULL, 
  	SUBJECT_ID INT NOT NULL, 
  	HADM_ID INT NOT NULL, 
  	ICUSTAY_ID INT NOT NULL, 
  	DBSOURCE VARCHAR(20) NOT NULL, 
  	FIRST_CAREUNIT VARCHAR(20) NOT NULL, 
  	LAST_CAREUNIT VARCHAR(20) NOT NULL, 
  	FIRST_WARDID SMALLINT NOT NULL, 
  	LAST_WARDID SMALLINT NOT NULL, 
  	INTIME VARCHAR(20) NOT NULL, 
  	OUTTIME VARCHAR(20), 
  	LOS DOUBLE PRECISION, 
  	CONSTRAINT icustay_icustayid_unique UNIQUE (ICUSTAY_ID), 
  	CONSTRAINT icustay_rowid_pk PRIMARY KEY (ROW_ID) 
  );


CREATE TABLE Warehouse.PATIENTS 
  (
	ROW_ID INT NOT NULL, 
  	SUBJECT_ID INT NOT NULL, 
  	GENDER VARCHAR(5) NOT NULL, 
  	DOB VARCHAR(20) NOT NULL, 
  	DOD VARCHAR(20), 
  	DOD_HOSP VARCHAR(20), 
  	DOD_SSN VARCHAR(20), 
  	EXPIRE_FLAG INT NOT NULL, 
    CONSTRAINT pat_subid_unique UNIQUE (SUBJECT_ID), 
    CONSTRAINT pat_rowid_pk PRIMARY KEY (ROW_ID) 
  );