--Date Dimension (Needs PK's - Possible Auto Increment)

CREATE TABLE Dim.[Date] (
	HADM_ID INT,
	ADMITTIME VARCHAR(20),
	DISCHTIME VARCHAR(20),
	DEATHTIME VARCHAR(20),
	INTIME VARCHAR(20),
	OUTIME VARCHAR(20),
	EDREGTIME VARCHAR(20),
	EDOUTTIME VARCHAR(20),
	CHARTTIME VARCHAR(40),
	STORETIME VARCHAR(40),
);

INSERT INTO Dim.[Date] (HADM_ID, INTIME, OUTIME)
SELECT HADM_ID, INTIME, OUTTIME
FROM Stage.ICUSTAYS;

INSERT INTO Dim.[Date] (DISCHTIME, DEATHTIME, EDREGTIME, EDOUTTIME)
SELECT DISCHTIME, DEATHTIME, EDREGTIME, EDOUTTIME
FROM Stage.ADMISSIONS;

INSERT INTO Dim.[Date] (CHARTTIME, STORETIME)
SELECT CHARTTIME, STORETIME
FROM Stage.CHARTEVENTS; -- Need to do

-- Patient Dimension

CREATE TABLE Dim.Patient (
	Subject_ID INT,
	Gender VARCHAR(5),
	DOB VARCHAR(45),
	DOD VARCHAR(20),
	Ethnicity VARCHAR(200)
);

INSERT INTO Dim.Patient (Subject_ID, Gender, DOB, DOD)
SELECT SUBJECT_ID, GENDER, DOB, DOD
FROM Stage.PATIENTS;

INSERT INTO Dim.Patient (Ethnicity)
SELECT ETHNICITY
FROM Stage.ADMISSIONS;

-- Hospital Dimension

CREATE TABLE Dim.Hospital (
	ICUSTAY_ID INT,
	EventType VARCHAR(20),
	AdmissionType VARCHAR(50),
	AdmissionLocation VARCHAR(50),
	DischargeLocation VARCHAR(50),
	LengthOfStay DOUBLE PRECISION
);

INSERT INTO Dim.Hospital (EventType)
SELECT EVENTTYPE
FROM Stage.TRANSFERS;

INSERT INTO Dim.Hospital (AdmissionType, AdmissionLocation, DischargeLocation)
SELECT ADMISSION_TYPE, ADMISSION_LOCATION, DISCHARGE_LOCATION
FROM Stage.ADMISSIONS;

INSERT INTO Dim.Hospital (ICUSTAY_ID, LengthOfStay)
SELECT ICUSTAY_ID, LOS
FROM Stage.ICUSTAYS;

-- Diagnosis Dimension

CREATE TABLE Dim.Diagnosis (
	Item_ID INT,
	Diagnosis VARCHAR(255),
	Category VARCHAR(100),
	Label VARCHAR(200)
);

INSERT INTO Dim.Diagnosis (Diagnosis)
SELECT DIAGNOSIS
FROM Stage.ADMISSIONS

INSERT INTO Dim.Diagnosis (Item_ID, Category, Label)
SELECT ITEMID, CATEGORY, LABEL
FROM Stage.D_ITEMS


--Length of Stay Fact

CREATE TABLE Fact.LengthOfStay (
	HADM_ID INT NOT NULL REFERENCES Dim.[Date](HADM_ID),
	Subject_ID INT NOT NULL REFERENCES Dim.Patient(SUBJECT_ID),
	ICUSTAY_ID INT NOT NULL REFERENCES Dim.Hospital(ICUSTAY_ID),
	Item_ID INT NOT NULL REFERENCES Dim.Diagnosis(ITEMID)
);